language: csharp
solution: src/CoCoL.sln
install:
  - nuget restore src/CoCoL.sln
  - nuget install NUnit.Runners -Version 3.4.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/CoCoL.sln
  - ls -lah ./testrunner
  - ls -lah ./testrunner/NUnit.ConsoleRunner.3.4.0
  - ls -lah ./testrunner/NUnit.ConsoleRunner.3.4.0/tools
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.0/tools/nunit3-console.exe ./src/UnitTest/bin/Release/UnitTest.exe
