language: csharp
solution: src/CoCoL.sln
install:
  - nuget restore src/CoCoL.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/CoCoL.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/UnitTest/bin/Release/UnitTest.dll